import './style.css'

let ws: WebSocket;
let roomId = '';
let myName = '';
let myTeam: 'red' | 'blue' | null = null;
let myRole: 'spymaster' | 'operative' | null = null;
let state: any = null;
let availableWordSets: Record<string, number> = {};
let selectedWordSets: string[] = ['English (Original)'];
let customWordsText = '';
let autogeneratedGameId = 'game1';
let timerMinutes = 5;
let timerSeconds = 0;
let timerEnabled = false;
let enforceTimerEnabled = false;
let timerInterval: number | null = null;

// Settings (persisted in localStorage)
interface AppSettings {
  fullscreen: boolean;
  colorBlind: boolean;
  darkMode: boolean;
  spymasterMayGuess: boolean;
}

function loadSettings(): AppSettings {
  try {
    return JSON.parse(localStorage.getItem('settings') || '{}');
  } catch { return {} as AppSettings; }
}

function saveSettings(s: AppSettings) {
  try { localStorage.setItem('settings', JSON.stringify(s)); } catch {}
}

let settings: AppSettings = loadSettings();

const app = document.querySelector<HTMLDivElement>('#app')!;

// ─── Favicon Turn Indicator ─────────────────────────────────────────────────

const defaultFavicon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAA8SURBVHgB7dHBDQAgCAPA1oVkBWdzPR84kW4AD0LCg36bXJqUcLL2eVY/EEwDFQBeEfPnqUpkLmigAvABK38Grs5TfaMAAAAASUVORK5CYII=';
const blueTurnFavicon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAmSURBVHgB7cxBAQAABATBo5ls6ulEiPt47ASYqJ6VIWUiICD4Ehyi7wKv/xtOewAAAABJRU5ErkJggg==';
const redTurnFavicon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAmSURBVHgB7cwxAQAACMOwgaL5d4EiELGHoxGQGnsVaIUICAi+BAci2gJQFUhklQAAAABJRU5ErkJggg==';

function setFavicon(href: string) {
  let link = document.getElementById('favicon') as HTMLLinkElement;
  if (!link) {
    link = document.createElement('link');
    link.id = 'favicon';
    link.rel = 'shortcut icon';
    link.type = 'image/png';
    document.head.appendChild(link);
  }
  link.href = href;
}

function updateFavicon() {
  if (!state || state.winner) {
    setFavicon(defaultFavicon);
  } else {
    setFavicon(state.currentTurn === 'blue' ? blueTurnFavicon : redTurnFavicon);
  }
}

// ─── URL-based Game Joining ─────────────────────────────────────────────────

function getGameIdFromUrl(): string | null {
  const p = window.location.pathname.replace(/^\//, '');
  return p || null;
}

// ─── WebSocket Connection ───────────────────────────────────────────────────

function connect(wordSet?: string[]) {
  const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  const host = window.location.host || 'localhost:8080';
  ws = new WebSocket(`${protocol}//${host}`);
  ws.onopen = () => ws.send(JSON.stringify({
    type: 'join', name: myName, roomId,
    wordSet: wordSet,
    timerDurationMs: timerEnabled ? (timerMinutes * 60 * 1000 + timerSeconds * 1000) : 0,
    enforceTimer: timerEnabled && enforceTimerEnabled,
  }));
  ws.onmessage = (msg) => {
    const data = JSON.parse(msg.data);
    if (data.type === 'init') {
      availableWordSets = data.wordSets || {};
      autogeneratedGameId = data.autogeneratedGameId || 'game1';
      render();
    }
    if (data.type === 'state') {
      state = data.state;
      myTeam = state.me.team;
      myRole = state.me.role;
      updateFavicon();
      startTimerInterval();
      render();
    }
  };
}

function joinGame() {
  myName = (document.getElementById('name') as HTMLInputElement).value;
  roomId = (document.getElementById('room') as HTMLInputElement).value;
  if (!myName || !roomId) return alert("Enter name and room");

  // Build word set from selections
  let combinedWords: string[] = [];
  // For simplicity, if custom words selected, parse them
  if (selectedWordSets.includes('Custom') && customWordsText.trim()) {
    combinedWords = customWordsText.split(',').map(w => w.trim().toUpperCase()).filter(w => w.length > 0);
  }
  // We send selectedWordSets names; server has the full word lists
  // For now, just send the default WORDS (server handles it)

  // Update URL
  window.history.pushState({}, '', '/' + roomId);
  connect(combinedWords.length >= 25 ? combinedWords : undefined);
}

function setRole(team: 'red'|'blue', role: 'spymaster'|'operative') {
  ws.send(JSON.stringify({ type: 'setRole', team, role }));
}

function giveClue() {
  const word = (document.getElementById('clue-word') as HTMLInputElement).value;
  const count = (document.getElementById('clue-count') as HTMLInputElement).value;
  if (!word || !count) return;
  ws.send(JSON.stringify({ type: 'giveClue', word, count }));
}

function guess(cardId: number) {
  if (myRole === 'spymaster' && !settings.spymasterMayGuess) return;
  if (myRole !== 'operative' && !(myRole === 'spymaster' && settings.spymasterMayGuess)) return;
  if (state.currentTurn !== myTeam || !state.clue || state.winner) return;
  ws.send(JSON.stringify({ type: 'guess', cardId }));
}

function endTurn() {
  if (state.currentTurn !== myTeam || state.winner) return;
  ws.send(JSON.stringify({ type: 'endTurn' }));
}

function newGame() {
  if (!state.winner && !confirm('Do you really want to start a new game?')) return;
  ws.send(JSON.stringify({
    type: 'newGame',
    timerDurationMs: timerEnabled ? (timerMinutes * 60 * 1000 + timerSeconds * 1000) : 0,
    enforceTimer: timerEnabled && enforceTimerEnabled,
  }));
}

// ─── Timer ──────────────────────────────────────────────────────────────────

function startTimerInterval() {
  if (timerInterval) clearInterval(timerInterval);
  if (state?.timerDurationMs > 0 && !state?.winner) {
    timerInterval = window.setInterval(() => {
      const timerEl = document.getElementById('game-timer');
      if (!timerEl || !state) return;
      const elapsed = Date.now() - new Date(state.roundStartedAt).getTime();
      const remaining = Math.max(0, state.timerDurationMs - elapsed);
      const totalSec = Math.ceil(remaining / 1000);
      const min = Math.floor(totalSec / 60);
      const sec = totalSec % 60;
      const color = totalSec <= 10 ? '#E22' : totalSec <= 30 ? '#F70' : '';
      timerEl.style.color = color;
      timerEl.textContent = `${String(min).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
      timerEl.setAttribute('aria-label', `Time remaining: ${min}:${String(sec).padStart(2, '0')}`);
      if (remaining <= 0 && state.enforceTimer && state.currentTurn === myTeam && myRole === 'operative') {
        endTurn();
      }
    }, 1000);
  }
}

// ─── Settings Toggle ────────────────────────────────────────────────────────

function toggleSetting(key: keyof AppSettings) {
  (settings as any)[key] = !(settings as any)[key];
  saveSettings(settings);
  if (key === 'darkMode') document.body.classList.toggle('dark-mode', !!settings.darkMode);
  render();
}

// Apply dark mode on load
if (settings.darkMode) document.body.classList.add('dark-mode');

// ─── Render ─────────────────────────────────────────────────────────────────

let currentView: 'lobby' | 'game' | 'settings' = 'lobby';

function render() {
  if (!state && currentView === 'lobby') {
    const urlGameId = getGameIdFromUrl();
    const defaultId = urlGameId || autogeneratedGameId;
    app.innerHTML = `
      <h1>Codenames</h1>
      <p class="intro">Play Codenames online across multiple devices on a shared board. To create a new game or join an existing game, enter a game identifier and click 'GO'.</p>
      <input id="name" placeholder="Your Name" aria-label="your name" />
      <input id="room" placeholder="Room ID" value="${defaultId}" aria-label="game identifier" />

      <div class="timer-settings">
        <label><input type="checkbox" id="timer-toggle" ${timerEnabled ? 'checked' : ''} /> Timer</label>
        ${timerEnabled ? `
          <div class="timer-duration">
            <span>Duration:</span>
            <input type="number" id="timer-min" min="0" max="59" value="${timerMinutes}" style="width:50px" aria-label="minutes" />
            <label>m</label>
            <input type="number" id="timer-sec" min="0" max="59" value="${timerSeconds}" style="width:50px" aria-label="seconds" />
            <label>s</label>
            <label><input type="checkbox" id="enforce-timer" ${enforceTimerEnabled ? 'checked' : ''} /> Enforce timer</label>
          </div>
        ` : ''}
      </div>

      <div class="custom-words-section">
        <label>Custom Words (comma-separated, min 25):</label>
        <textarea id="custom-words" aria-label="custom word set" placeholder="word1, word2, word3...">${customWordsText}</textarea>
      </div>

      <button id="join-btn">Go</button>
    `;
    document.getElementById('join-btn')!.onclick = joinGame;
    document.getElementById('timer-toggle')?.addEventListener('change', (e) => {
      timerEnabled = (e.target as HTMLInputElement).checked;
      render();
    });
    document.getElementById('timer-min')?.addEventListener('change', (e) => { timerMinutes = parseInt((e.target as HTMLInputElement).value) || 0; });
    document.getElementById('timer-sec')?.addEventListener('change', (e) => { timerSeconds = parseInt((e.target as HTMLInputElement).value) || 0; });
    document.getElementById('enforce-timer')?.addEventListener('change', (e) => { enforceTimerEnabled = (e.target as HTMLInputElement).checked; });
    document.getElementById('custom-words')?.addEventListener('input', (e) => { customWordsText = (e.target as HTMLTextAreaElement).value; });
    return;
  }

  if (currentView === 'settings') {
    app.innerHTML = `
      <div class="settings-panel" role="group" aria-label="settings">
        <button id="close-settings" aria-label="close settings">✕ Close</button>
        <h2>SETTINGS</h2>
        <label><input type="checkbox" data-setting="fullscreen" ${settings.fullscreen ? 'checked' : ''} /> Full-screen — Enlarge the board to take up the whole page.</label>
        <label><input type="checkbox" data-setting="colorBlind" ${settings.colorBlind ? 'checked' : ''} /> Color-blind — Add patterned borders to help distinguish teams.</label>
        <label><input type="checkbox" data-setting="darkMode" ${settings.darkMode ? 'checked' : ''} /> Dark — Darken the mood.</label>
        <label><input type="checkbox" data-setting="spymasterMayGuess" ${settings.spymasterMayGuess ? 'checked' : ''} /> Spymaster may guess — Clicking a word from spymaster view reveals it.</label>
      </div>
    `;
    document.getElementById('close-settings')!.onclick = () => { currentView = 'game'; render(); };
    document.querySelectorAll('[data-setting]').forEach(el => {
      el.addEventListener('change', () => toggleSetting((el as HTMLInputElement).dataset.setting as keyof AppSettings));
    });
    return;
  }

  if (state && !myTeam) {
    app.innerHTML = `
      <h2>Room: ${roomId}</h2>
      <div id="share" aria-label="share link">Send this link to friends: <a class="url" href="${window.location.href}">${window.location.href}</a></div>
      <div>
        <h3>Join Red</h3>
        <button id="red-spy" aria-label="join red as spymaster">Spymaster</button> <button id="red-op" aria-label="join red as operative">Operative</button>
      </div>
      <div>
        <h3>Join Blue</h3>
        <button id="blue-spy" aria-label="join blue as spymaster">Spymaster</button> <button id="blue-op" aria-label="join blue as operative">Operative</button>
      </div>
    `;
    document.getElementById('red-spy')!.onclick = () => setRole('red', 'spymaster');
    document.getElementById('red-op')!.onclick = () => setRole('red', 'operative');
    document.getElementById('blue-spy')!.onclick = () => setRole('blue', 'spymaster');
    document.getElementById('blue-op')!.onclick = () => setRole('blue', 'operative');
    return;
  }

  if (!state) return;

  currentView = 'game';
  const extraClasses = [
    myRole === 'spymaster' ? 'codemaster' : 'player',
    settings.colorBlind ? 'color-blind' : '',
    settings.darkMode ? 'dark-mode' : '',
    settings.fullscreen ? 'full-screen' : '',
  ].filter(Boolean).join(' ');

  const remaining = (team: string) => state.board.filter((c: any) => c.type === team && !c.revealed).length;
  const startingTeam = state.redLeft + remaining('red') > state.blueLeft + remaining('blue') ? 'red' : 'blue';

  app.innerHTML = `
    <div id="game-view" class="${extraClasses}">
      ${!settings.fullscreen ? `<div id="share" aria-label="share link">Send this link to friends: <a class="url" href="${window.location.href}">${window.location.href}</a></div>` : ''}
      ${state.timerDurationMs ? `<div id="game-timer" role="img" aria-label="timer">--:--</div>` : ''}
      <div class="status-bar">
        <div class="status-red" aria-label="${state.redLeft} red words remaining">Red: ${state.redLeft} left</div>
        <div>Turn: <span class="status-${state.currentTurn}">${state.winner ? `${state.winner.toUpperCase()} WINS!` : state.currentTurn.toUpperCase()}</span></div>
        <div class="status-blue" aria-label="${state.blueLeft} blue words remaining">Blue: ${state.blueLeft} left</div>
      </div>
      ${state.winner ? `<h2>Winner: <span class="status-${state.winner}">${state.winner.toUpperCase()}</span></h2>` : ''}
      ${state.clue ? `<h3 aria-label="current clue">Clue: ${state.clue.word} (${state.clue.count})</h3>` : ''}
      <div class="board">
        ${state.board.map((c: any) => `
          <div class="card type-${c.type} ${c.revealed ? 'revealed' : ''} ${settings.colorBlind ? 'cb-' + c.type : ''}"
               data-id="${c.id}"
               role="button"
               aria-disabled="${c.revealed || !!state.winner}"
               aria-label="${c.word.toLowerCase()}${c.revealed || myRole === 'spymaster' || state.winner ? ', ' + (c.type === 'assassin' ? 'assassin' : c.type) : ''}, ${c.revealed ? 'revealed word' : 'hidden word'}">
            ${c.word}
          </div>
        `).join('')}
      </div>
      <div class="controls" role="toolbar">
        <button id="settings-btn" class="gear" aria-label="settings">⚙</button>
        ${myRole === 'spymaster' && myTeam === state.currentTurn && !state.clue && !state.winner ? `
          <input id="clue-word" placeholder="Clue word" aria-label="clue word" />
          <input id="clue-count" type="number" min="1" max="9" placeholder="#" style="width: 50px;" aria-label="clue count" />
          <button id="give-clue" aria-label="give clue">Give Clue</button>
        ` : ''}
        ${myRole === 'operative' && myTeam === state.currentTurn && state.clue && !state.winner ? `
          <button id="end-turn" aria-label="end ${state.currentTurn}'s turn">End Turn</button>
        ` : ''}
        <button id="new-game-btn" aria-label="next game">Next Game</button>
      </div>
      <div class="log" aria-label="game log">
        ${state.log.map((l: string) => `<div>${l}</div>`).join('')}
      </div>
    </div>
  `;

  document.querySelectorAll('.card').forEach(el => {
    el.addEventListener('click', () => {
      guess(Number((el as HTMLElement).dataset.id));
    });
  });

  document.getElementById('give-clue')?.addEventListener('click', giveClue);
  document.getElementById('end-turn')?.addEventListener('click', endTurn);
  document.getElementById('new-game-btn')?.addEventListener('click', newGame);
  document.getElementById('settings-btn')?.addEventListener('click', () => { currentView = 'settings'; render(); });

  // Start timer display
  startTimerInterval();
}

// Handle Escape key to close settings
window.addEventListener('keydown', (e) => {
  if (e.key === 'Escape' && currentView === 'settings') {
    currentView = 'game';
    render();
  }
});

// Check URL for game ID on load
const urlGameId = getGameIdFromUrl();
if (urlGameId) {
  roomId = urlGameId;
}

render();
